security:
    encoders:
        AppBundle\Entity\User:    { algorithm: sha512, iterations: 10 }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
             entity: { class: AppBundle\Entity\User }

    firewalls:
        main:
            pattern: ^/*
            provider: users
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: dashboard
            logout:
                path:       logout
                target:     login

    access_control:
        - { path: ^/admin/*, roles: ROLE_USER}
        - { path: ^/system/*, roles: ROLE_USER}
