<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;

/**
 * ProyectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectRepository extends EntityRepository {
    public function getCount() {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT COUNT (p)
            FROM AppBundle:Proyect p
        ');
        return $query->getSingleScalarResult();
    }

    public function getProyects($start = 0, $length = 10, $search) {
        $searchDQL = "";
        if ($search) {
            $searchDQL .= "WHERE p.name LIKE '%$search%'
                OR p.description LIKE '%$search%'
                OR p.created_time LIKE '%$search%'
            ";
        }
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT p.name, p.description, p.created_time, p.id, p.enabled
            FROM AppBundle:Proyect p
            ' . $searchDQL . '
            ORDER BY p.created_time DESC
        ');
        $query->setFirstResult($start);
        if ($length != 'all')
            $query->setMaxResults($length);

        return $query->getArrayResult();
    }

    public function getProyectWithTaskAssignedByUserId($userId = null){


        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT p.name, p.description, p.created_time, p.id, p.enabled
            FROM AppBundle:Proyect p
            ' . $searchDQL . '
            ORDER BY p.created_time DESC
        ');
    }
}
