<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskNoteRepository extends EntityRepository {
    public function getCount($id_task) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT COUNT (tn)
            FROM AppBundle:TaskNote tn JOIN tn.task t
            WHERE t.id = :id
        ');
        $query->setParameter('id', $id_task);
        return $query->getSingleScalarResult();
    }

    public function getTaskNotes($start = 0, $length = 10, $search, $id_task) {
        $searchDQL = "";
        if ($search) {
            $searchDQL .= " AND (tn.note LIKE '%$search%'
                OR tn.createdOn LIKE '%$search%'
                OR u.name LIKE '%$search%')
            ";
        }
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT tn.id, tn.note, tn.createdOn, u.name as user
            FROM AppBundle:TaskNote tn JOIN tn.user u JOIN tn.task t
            WHERE t.id = :id' . $searchDQL . '
            ORDER BY tn.createdOn DESC
        ');
        $query->setParameter('id', $id_task);
        $query->setFirstResult($start);
        if ($length != 'all')
            $query->setMaxResults($length);

        return $query->getArrayResult();
    }
}
